"""add daily_calorie_goal to user

Revision ID: 6b6603631f72
Revises: ca64e174b752
Create Date: 2026-02-17 18:35:23.563482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b6603631f72"
down_revision: Union[str, None] = "ca64e174b752"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "daily_calorie_goal", sa.Integer(), server_default="2000", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "daily_calorie_goal")
    # ### end Alembic commands ###
